name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: GETTING PULL AND INSTALLING BUNDLE
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          sshpass -p $PASSWORD ssh -p 5001 -o StrictHostKeyChecking=no server@125.99.200.202 "cd /home/server/file-server-code/ && git pull origin master && echo $PASSWORD | sudo -S gem install bundler && bundle install"

      - name: STARTING SERVER
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          PID=$(sshpass -p $PASSWORD ssh -p 5001 -o StrictHostKeyChecking=no server@125.99.200.202 "screen -ls | grep FILE-SERVER | cut -d'.' -f1 | awk '{print \$1}'")
          if [ -n "$PID" ]; then
            sshpass -p $PASSWORD ssh -p 5001 -o StrictHostKeyChecking=no server@125.99.200.202 "kill -9 $PID"
          fi
          sshpass -p $PASSWORD ssh -p 5001 -o StrictHostKeyChecking=no server@125.99.200.202 "cd /home/server/file-server-code/ && screen -dmS FILE-SERVER rails s -p 3050 -b 192.168.0.100"
