name: Deploy Rails app

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Run command on remote server
        #run: sshpass -p "Webkorps@123456" ssh -p 5001 server@125.99.200.202 "cd /home/server/ && mkdir TESTFOLDERWITHGITHUB"
        run: cd /home/server/ALL\ SERVER\ CODES/file-server-code/ && sshpass -p "Webkorps@123456" ssh -p 5001 server@125.99.200.202 -T "./STARTSERVER.sh"
