name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Install dependencies
      #   run: |
      #     sudo apt-get update && sudo apt-get install -y \
      #       build-essential \
      #       libpq-dev \
      #       nodejs
      #     sudo chown -R $USER:$USER /var/lib/gems/3.0.0
      #     gem install --user-install bundler          
      #     export PATH="$HOME/.local/share/gem/ruby/3.0.0/bin:$PATH"
      #     bundle install --jobs 4 --retry 3

      - name: DEPLOY APP USING TERMINAL COMMANDS
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          sshpass -p $PASSWORD ssh -p 5001 -o StrictHostKeyChecking=no server@125.99.200.202 "cd /home/server/file-server-code/ && git pull origin master && gem install bundler && bundle install"      