name: Deploy to On-Premises

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        sudo apt-get update
        bundle install
    - name: Deploy
      run: |
        ssh server@125.99.200.202 "cd /home/server/ALL\ SERVER\ CODES/file-server-code && git pull && bundle install && yarn install && RAILS_ENV=production rails assets:precompile && touch tmp/restart.txt"
