name: Deploy Rails app

on:
  push:
    branches: [master]
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install ssh-actions
      uses: appleboy/ssh-actions@master

    - name: Run playbook
      uses: appleboy/ssh-actions@master
      with:
        host: 125.99.200.202
        username: your-username
        port: 22
        script: |
          cd /home/server/
          mkdir TESTFOLDERWITHGITHUB
          
