name: Deploy to On-Premises

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{github.ref}}

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: Install Dependencies
      run: |
        npm install
        bundle install
    - name: Deploy
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass
        sshpass -p "$SYSTEM_PASSWORD" ssh -p 6000 server@125.99.200.202 "cd /home/server/ALL\ SERVER\ CODES/file-server-code && git pull && bundle install && RAILS_ENV=production rails assets:precompile && touch tmp/restart.txt"
