name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
            build-essential \
            libpq-dev \
            nodejs
          sudo chown -R $USER:$USER /var/lib/gems/3.0.0
          gem install --user-install bundler          
          export PATH="$HOME/.local/share/gem/ruby/3.0.0/bin:$PATH"
          bundle install --jobs 4 --retry 3

      - name: Build and package application
        run: |
          rails assets:precompile RAILS_ENV=production
          rails db:migrate RAILS_ENV=production
          tar -czf app.tar.gz .

      - name: Transfer package to on-premise machine
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          sshpass -p $PASSWORD scp -P 5001 -o StrictHostKeyChecking=no app.tar.gz $USERNAME@125.99.200.202:/home/server/

      - name: Deploy application on on-premise machine
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          sshpass -p $PASSWORD ssh -p 5001 -o StrictHostKeyChecking=no $USERNAME@125.99.200.202 "cd /home/server/ && tar -xzf app.tar.gz && sudo systemctl restart myapp.service"
