name: Deploy Rails app

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Navigate to Directory
        run: cd /home/server/ALL\ SERVER\ CODES/file-server-code/ && git pull origin master

      - name: check directory
        run: ls

      - name: Start Server
        run: |
          sshpass -p "Webkorps@123456" ssh -tt -p 5001 server@125.99.200.202 '
            cd /home/server/ALL\ SERVER\ CODES/file-server-code/
            git pull origin master
            pwd
            /home/server/.rvm/gems/ruby-3.0.0/bin/bundle install
            nohup rails s -p 3050 -b 192.168.0.100 > server.log 2>&1 &
            rails s
          '
