name: Deploy Rails app

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Navigate to Directory
        run: cd /home/server/ALL\ SERVER\ CODES/file-server-code/ && git pull origin master

      - name: Install Bundle
        run: bundle install

      - name: Start Server
        run: sshpass -p "Webkorps@123456" ssh -p 5001 server@125.99.200.202 && ./STARTSERVER.sh
